### ISSUE TITLE
Custom extraction file names

### ISSUE THREAD

**Issue by cmetzbower** [daniel-sc/ng-extract-i18n-merge#10]
Our files were not called messages.xlf.  Might have a config option to pass in your file name.  During the install it could be picked up from angular.json "outFile."  It looked like it wouldn't matter for targets, but it is definitely hardcoded in the normalize section.

Worked beautifully got it up and running in a few minutes as to the days I spent trying to learn and fix up the old xliffmerge tool.  Much appreciated!  As my co-worker stated.. we'll rename all our extractions to daniel as long as it works!

**Comment by daniel-sc** [comment]
Hi @cmetzbower 

thanks for bringing this up!
Would you mind checking if v1.2.0 works better?

**Comment by cmetzbower** [comment]
@daniel-sc  
Awesome, I will check it out.  We have moved forward with messages.xlf as we had no real reason for using i18n.xlf, but I'll reset to an older commit and see if everything works just using ng add.  Hopefully someone will like this option in the future.
