### ISSUE TITLE
defaultLanguage parameter is missing from ngx-i18nsupport

### ISSUE THREAD

**Issue by cargongo** [daniel-sc/ng-extract-i18n-merge#11]
Hi!

We've migrated from ngx-i18nsupport to ng-extract-i18n-merge and it works almost perfect! The only thing we miss is the defaultLanguage parameter.

![default](https://user-images.githubusercontent.com/11225286/159241781-d2232a46-0408-4c7f-b7bc-ec577c275574.png)

Before, we run "ng extract-i18n" + "ng run [project]:xliffmerge" and we got our messages.es.xlf (default language) with all state tags as "final".

Currently, we run "ng extract-i18n" + "ng run [project]:extract-i18n-merge" and all new tags are marked as "new". We solved it adding " && sed -i 's|state=\"new\"|state=\"final\"|g' src/i18n/messages.es.xlf" to our script but it would be great if we could do this through a parameter like the other library.

Thank you for your work!

**Comment by daniel-sc** [comment]
Hi @cargongo 
thanks for bringing this up!
Would you mind checking if v1.2.0 works better?

**Comment by cargongo** [comment]
Solved! Thank you!
