### ISSUE TITLE
$localize in library not working with esbuild

### ISSUE THREAD

**Issue by gongAll** [daniel-sc/ng-extract-i18n-merge#116]
originally on https://github.com/angular/angular-cli/issues/28576

When I use $localize in a library and use it as a dependency on my app, it works fine when I build the app with @angular-devkit/build-angular:browser however when I switch it to @angular-devkit/build-angular:browser-esbuild it suddenly throws the following runtime error, which prevents the app from properly loading:

Uncaught TypeError: $localize is not a function.

Minimal repro: https://github.com/gongAll/angular-cli-28576

**Comment by daniel-sc** [comment]
I'll look into this asap

**Comment by gongAll** [comment]
Well that makes no sense since I used their builder and the error would not happen. Would you mind supplying a repro to show them? You can fork mine to save time. 

Only could reproduce it with your library, which tells me that it could be due to the need of updating the dependencies you have from angular.

**Comment by daniel-sc** [comment]
Ok, I'll fork your repo for a reproduction without this lib

**Comment by gongAll** [comment]
Thanks, I appreciate your efforts.

Will follow up closely, cheers

@daniel-sc

**Comment by daniel-sc** [comment]
@gongAll I removed the lib from your repository and did a clean build and still get the same error - see https://github.com/gongAll/angular-cli-28576/pull/1

**Comment by gongAll** [comment]
Ok, will check it as soon as possible,

Cheers.
