### ISSUE TITLE
Invalid attribute name error on merge and normalizing step

### ISSUE THREAD

**Issue by sporatrx** [daniel-sc/ng-extract-i18n-merge#121]
**Bug Description** 
I am experiencing a problem executing extract-i18n on an existing project of mine since some update as it did work before. Unfortunately I do not know when this error did start popping up and to which update it thus might be related.

When executing extract-i18n on my project it successfully extracts the strings into my messages.xlf file but fails at the next step when trying to merge and normalize the first localized messages.xlf file (In my case it is named messages.de-DE.xlf.) with the error:

```
An unhandled exception occurred: Invalid attribute name
Line: 0
Column: 68
Char: "
See "/private/var/folders/bt/l2td87q16sj_vlx9qbt9qgbc0000gp/T/ng-2YQAOp/angular-errors.log" for further details.
```
![image](https://github.com/user-attachments/assets/a5253e0e-6093-4b27-94b2-36fe4da29d9b)

This seems to be some kind of sax.js error as far as I understand. I checked both the messages.xlf and messages.de-DE.xlf files if they are valid XML. Both are fine. 

Can you point me into the right direction what might cause this error? I can also provide you the files in question if needed. I first have to check back with my employer though if this is okay.

**Expected behavior**
All xlf files should be merged and updated with newly extracted strings from the messages.xlf file.

**Version**
 - Angular: 18
 - OS: MacOS Sequia 15.1.1 (24B91)
 - nodejs: v20.14.0
 - ng-extract-i18n-merge version: 2.12.0

**Comment by daniel-sc** [comment]
@sporatrx I'd suspect a malformed translation file. Would it be possible to share your configuration (angular.json) and your translation file either here or privately?

**Comment by sporatrx** [comment]
@daniel-sc Sorry for the late replay. I had to clarify if it is okay to share these files. I sent you an email with the needed files to your address.

**Comment by mjschranz** [comment]
Hi @daniel-sc and @sporatrx 

I've been running into the same problem for projects. When you mention what you want shared from angular.json, do you mean just the following?


```

        "extract-i18n": {

          "builder": "ng-extract-i18n-merge:ng-extract-i18n-merge",

          "options": {

            "buildTarget": "pdf-template-mpr:build",

            "format": "xlf",

            "outputPath": "src/locale",

            "targetFiles": ["messages.fr.xlf", "messages.en.xlf"]

          }

        },
```

Sadly I can't attach XLF files here directly.

**Comment by daniel-sc** [comment]
@sporatrx @mjschranz can you please check if v2.13.1 resolves it for you?
(Note: the issue was a quote (`"` / `&quot;`) in one of the ids)

**Comment by sporatrx** [comment]
I can verify that extracting strings now works again for me.
![image](https://github.com/user-attachments/assets/40789c49-d90c-4929-96b4-568d9a5ba56c)
Thank you very much for the quick help.

**Comment by mjschranz** [comment]
I can also verify this fixed the issue I saw.

Thanks!

**Comment by mjschranz** [comment]
@daniel-sc Related to this error, I'm seeing something else similar after using this newer 2.13.1 patch but in another project that also uses XLF files. The 2.13.1 patch did still work for one project.

<img width="901" alt="image001" src="https://github.com/user-attachments/assets/92095884-61d5-42f2-a576-60054ef5793c">

Any thoughts? What info might you need>

**Comment by daniel-sc** [comment]
@mjschranz Please create a new bug for this and share the relevant xlf files and angular.json (preferably in the bug - alternatively to daniel-schreiber@gmx.de)
