### ISSUE TITLE
includeContext not working?

### ISSUE THREAD

**Issue by Andrew-Marks-Trisept** [daniel-sc/ng-extract-i18n-merge#14]
Thank you so much for making this!  I'm hoping to replace [xliff merge](https://github.com/martinroob/ngx-i18nsupport) with it.  (I'm particularly excited to try `removeIdsWithPrefix`, which may replace an entire node script I had to write for our workflow).

**The issue**: When I try to use the `includeContext` flag, it doesn't seem to include notes from my source file.

_My config:_
```
"extract-i18n-merge": {
  "builder": "ng-extract-i18n-merge:ng-extract-i18n-merge",
  "options": {
    "format": "xlf2",
    "outputPath": "src/locale",
    "targetFiles": ["base-messages/messages.en-US.xlf", "base-messages/messages.es-MX.xlf"],
    "sourceLanguageTargetFile": "base-messages/messages.en-US.xlf",
    "sourceFile": "generated/source-messages.xlf",
    "fuzzyMatch": false,
    "includeContext": true
  }
}
```

_Sample from source:_
```
<unit id="core.pageTitles.account">
  <notes>
	<note category="location">src/app/account/account-routing.module.ts:17</note>
  </notes>
  <segment state="translated">
	<source>My Account</source>
	<target>Mi cuenta</target>
  </segment>
</unit>
```

_Sample from target:_
```
<unit id="core.pageTitles.account">
  <segment state="translated">
	<source>My Account</source>
	<target>Mi cuenta</target>
  </segment>
</unit>
```

**Comment by daniel-sc** [comment]
Hi @Andrew-Marks-Trisept 

thanks for reaching out - would you mind trying v1.2.1 and check if this fixes this issue?

**Comment by Andrew-Marks-Trisept** [comment]
Fixed, thank you.  Amazing response time!
