### ISSUE TITLE
More documentation and usage examples

### ISSUE THREAD

**Issue by tfohlmeister** [daniel-sc/ng-extract-i18n-merge#15]
Thanks for this cool tool! I am a bit confused though with what its actually supposed to do, maybe you could shine some light on it.

I *thought* you could use it to extract translation strings from multiple projects, merge them together and use one unified source translation file. I would've then generated target translations in an external tool and built multiple, localized angular apps from that like I already do with a single project.

However I played around with all the options but can't figure it out. Either my main source translation file is being overwritten by a single project or the translated target file.

Could you quickly explain the workflow when working with multiple source projects? Or is this tool supposed to do something completly different? Thanks! :-)

**Comment by daniel-sc** [comment]
Hi @tfohlmeister 

this tool is _not_ supposed to merge translations from multiple angular projects, but only merges new and existing translations of a single angular project.

Would you be interested in updating the README.md to make this more clear?

Your multi-project case seems like an interesting extension, but this would probably exceed the scope of this package.

**Comment by tfohlmeister** [comment]
Ah thats too bad! I am using this in a NX mono-repository and couldn't wrap my head around it, but I guess I should be looking for another tool then!

Thanks for clarifying :)
