### ISSUE TITLE
sourceLanguageTargetFile should always receive latest from HTML source?

### ISSUE THREAD

**Issue by Andrew-Marks-Trisept** [daniel-sc/ng-extract-i18n-merge#16]
Our app is coded in English and we consider it the default/base language.  Translations to other languages happen _from_ en-US _to_ the other cultures.  The HTML source code essentially is where we maintain our English verbiage.  Therefore, I've set `sourceLanguageTargetFile` to my en-US file because it never needs to be translated and all its units should always be `state="final"`.

The problem is when we make an update to a message in the HTML _without changing the ID_, that update is never propagated to the merged output files.  For "other" cultures it makes sense -- that's the whole point of merging so you don't automatically lose all your old translations.  But for the `sourceLanguageTargetFile` culture, can it just always update the target with the latest verbiage from the HTML?  I don't want to have to manually "translate" my en-US file from English to English, if that makes sense.

xliff merge did it this way and it worked well for us.  I'm not sure if there is a counter-argument I'm not thinking of.

For further context, we use a custom process with our i18n IDs.  Basically we increment a version number on the end of them when the verbiage has changed enough to warrant a new translation.  So if I'm totally changing the verbiage on something, I'd increment to a new ID and thus need to add all new translations in my target languages.  But if I'm just fixing a spelling mistake in the English version, I'd keep the ID the same and not need to touch anything else other than the HTML.  This also helps when repeatedly changing verbiage early in a project/feature, before any translations have actually been performed.  Ideally the en-US output file just stays in sync with the English HTML source code and is always considered "final".

Thanks for your consideration.

**Comment by daniel-sc** [comment]
@Andrew-Marks-Trisept can you please check if v1.2.2 fixes this?

**Comment by Andrew-Marks-Trisept** [comment]
It does.  Thanks!
