### ISSUE TITLE
includeContext removes multiple context-group

### ISSUE THREAD

**Issue by brokolja** [daniel-sc/ng-extract-i18n-merge#21]
First. Thank you for this plugin!!!

I think I found a lil bug. I had the same text to translate in multiple components and noticed that it was only translated in one of the components. It seems angular uses context-groups to translate multiple components. I used "includeContext": true to fix this but found the following even without it.

For example this is the original messages.xlf:

```
<trans-unit id="1547876271716599756" datatype="html">
        <source>Impressum</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app-routing.module.ts</context>
          <context context-type="linenumber">12</context>
        </context-group>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">4</context>
        </context-group>
      </trans-unit>
```

and this is what the plugin generates:

```
<trans-unit id="1547876271716599756" datatype="html">
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app-routing.module.ts</context>
          <context context-type="linenumber">12</context>
        </context-group>
        <source>Impressum</source>
        <target state="translated">Imprint</target>
      </trans-unit>
```

I would also recommend to set "includeContext": true as default in the plugin if I did not miss anything here.

Thank you!

**Comment by daniel-sc** [comment]
Hi @brokolja 

sorry for the late response! I tried to reproduce this and found the following:

1. The context-groups are _not_ used to "manage" translations in multiple files/occurrences but are purely informational for the translator. So when you apply the `i18n` attribute correctly to each occurrence, in every place the translation will be used. This is independent of the "includeContext" configuration. (If I'm missing something here, please provide a minimal reproduction - e.g. a git repository with a new angular project where the problem can be reproduced.)
2. When using `"includeContext": true` it is actually a bug, that all but one context is missing - I'll provide a fix for this!

Hope that helps!

**Comment by brokolja** [comment]
Can't recreate 2. with 1.2.3. 1. is also gone so I guess it was my fault or some magic. Awesome - Thank you!
