### ISSUE TITLE
Unexpected results / modification of existing xlf files

### ISSUE THREAD

**Issue by Giusti** [daniel-sc/ng-extract-i18n-merge#25]
Hey so I have been trying ng-extract-i18n-merge to see wether it can replace the old @ngx-i18nsupport/tooling (using 9 locales), but I ran into some problems.

Installation & Configuration went fine, but when I first executed it I got the following results:

angular.json
![image](https://user-images.githubusercontent.com/6214919/166229114-413c26a2-7746-4f6a-b7d5-2aac5b108932.png)

package.json
`"i18n-extract-merge": "ng build && ng run xxx:extract-i18n-merge",`

1)Already translated texts in state=translated were overritten
2)Order / Structure of .xlf files was completely modified 

**Example:**
As you can see the english word "Sender" was already translated to the german word "Absender" and it went from line 1388 to line 11

![image](https://user-images.githubusercontent.com/97685381/166227471-10124c18-28b7-47e4-bcee-599abc5c957d.png)

Is there any way to keep the existing translations by modifying the state attribute or via configuration?

3)FuzzySearch = true resulted in many mismatches mixing source & target of multiple texts

**Comment by daniel-sc** [comment]
@Giusti Thanks for reporting this. I'll look into the described bugs later this week. 

Remark:
- Currently entries are ordered by "id" - I'll add an option for stable order/sorting.

**Comment by Giusti** [comment]
@daniel-sc Thank you for the quick response.

I fiddled around a bit with the builder.js inside the ng-extract-i18n-merge dist folder:

sortPath: isXliffV2 ? '/xliff/file/unit/@id' : '/xliff/file/body/trans-unit/@id', ---> sortPath: null,

resulted in all trans-units with a non numerical id where kept at the same line and already translated units stayed the same

![image](https://user-images.githubusercontent.com/6214919/166415471-c93cfc40-b8c5-4282-a6d6-bdec7eb36f98.png)

while all numerical ids where modified / overritten and appended at the end of the file

![image](https://user-images.githubusercontent.com/6214919/166415586-f9fd7146-72e5-4c63-b856-747926d374c6.png)

**Comment by daniel-sc** [comment]
Hi @Giusti I tried to reproduce this problem but did not succeed yet. 
I think I did not yet fully understand your screenshots. Is it possible that the (source) text "Welcome!" is contained in multiple translation units? If so, why? What else could distinguishes the units where the translations are kept from the translations that are reset?
(If you'd be willing to create a minimal reproduction setup it would be great :) )

**Comment by Giusti** [comment]
Hey @daniel-sc really appreciate the support.

I have to investigate a bit further, I manually updated all trans-unit states to final and then executed and about 150 from 450 transunits on every language got a new id assigned and were overritten with state="new". 

I am not exactly sure why this logic behaves differently than the @ngx-i18nsupport/tooling, but it seems be related with the xlif-simple-merge -> getDestUnit method

I will try reproducce it or provide a small app where the same issue occurs, but it will take some time.

**Comment by Giusti** [comment]
@daniel-sc well quicker than expected but I found the issue and its pretty stupid...

I was using @local/cli (for extraction) & @ngx-i18nsupport/tooling (for the xliffmerge)
and now I replaced the whole script by your implementation of both extracting & merging (which is now using angulars cli extraction)

When I revert my base message.xlf file and only run the angular cli extraction without any merge, the modifications (overriding / resetting) already happens, which is then transferred to the other languages....

So it is not related to the merge part but rather the extraction part which seems to be different from what @locl/cli has been doing before.

**Comment by daniel-sc** [comment]
@Giusti not sure I can follow everything..
When you run `ng extract-i18n` only your `messages.xlf` should be updated - so it is not possible that translations are overwritting/reset - correct?
When you run `npm run extract-i18n-merge` (which internally runs `ng extract-i18n`), then a merge of new/changed texts/IDs from messages.xlf to your 9 target xlf files happens.
Could you please detail if the problem persists, or is solved?

**Comment by Giusti** [comment]
@daniel-sc sorry for the confusion.

So since I ran both extract & merge in a single command I did not notice, that the extract command was actually modifying already half of my base messages.xlf (replacing ids, removing targets, adding context groups)

And ofc after 50% of the base messages.xlf was modified and ids changed, also most of my target language files was then modified during the merge part of the script

it seems there is quite a huge difference between @locl/cli extraction and ng  extract-i18n extraction method.

I will try to get the base extraction sorted out and report back if then everything works as expected

**Comment by daniel-sc** [comment]
@Giusti did you succeed? The latest version 1.4.0 should have an improved ID matching (if you do _not_ disable fuzzy match). Please reopen, if this still does not work as expected!

**Comment by Giusti** [comment]
@daniel-sc I am nearly finished migrating the translations for all the languages but so far it looks good.
It would be really nice to have a param to be able to configure how sorting behaves. 

Most of the issues / work came from the switch from @locl/cli to angulars extraction script.

Thank you very much for supporting me really appreciate it.

**Comment by daniel-sc** [comment]
@Giusti there is a new "sort" config option - please check the updated readme.
You can configure the angular compiler to error on missing translations - see https://angular.io/guide/i18n-common-merge#angularjson-error-warning-example
