### ISSUE TITLE
Space trimming

### ISSUE THREAD

**Issue by YehorLitsov** [daniel-sc/ng-extract-i18n-merge#28]
Looks like `extract-i18n-merge` command trims spaces, but `extract-i18n` don't. I have cases when i don't need to trim them.
<img width="496" alt="Screenshot 2022-05-09 at 21 14 51" src="https://user-images.githubusercontent.com/68663734/167471745-98925e80-106f-49d6-802c-74cf130a2900.png">
```
<span
  class="link-ghost"
  i18n="Phone Verification"
> Change</span>
```
I have a space before `Change`. But as a result i have:
```
<trans-unit id="ba3ab8408e0985aaa20a3c83f77a8bc336a96ae4" datatype="html">
  <source>Change</source>
  <context-group purpose="location">
    ...
  </context-group>
  <note priority="1" from="description">Phone Verification</note>
</trans-unit>
```
May be there is any extra config except `collapseWhitespace`?
`"ng-extract-i18n-merge": "^1.4.0",`

**Comment by daniel-sc** [comment]
Hi @YehorLitsov 
Thanks for your feedback. This option is not yet available. Before adding it I'd like to understand why it is needed. In my experience these white spaces get trimmed in the `ng build` - so it makes no difference for the final output. But please let me know why you'd rather not have it trimmed!
Best
Daniel

**Comment by YehorLitsov** [comment]
Hi!
Yes, sorry, might be i provided incomplete information and forgot to greeting :)
`npm run extract-i18n` build everything without trimming, like i mentioned in first message, in such cases like this
```
<div>
  <ng-container>Some string </ng-container>
  <span>{{someValue}}</span>
  <span> some final.</span>
</div>
```
the result will be `Some string VALUE some final.`
But using `nom run extract-i18n-merge` the result after build will be `Some stringVALUEsome final.`
It's an issue for me, so i have to do something like this in each case:
```
<div>
  <ng-container>Some string</ng-container>
  <span>&nbsp;</span>
  <span>{{someValue}}</span>
  <span>&nbsp;</span>
  <span> some final.</span>
</div>
```

Before i used `npm run extract-i18n` and `@ngx-i18nsupport/tooling` with its xlf-merge, but after update to Angular 13 had an issue with lib. So that's why i switched to yours, and everything works great except this one small thing.
Thank you!
Best
Yehor

**Comment by daniel-sc** [comment]
@YehorLitsov you are right (angular compiler removes whitespaces _between_ nodes, but not within..)

**Comment by daniel-sc** [comment]
@YehorLitsov would you mind checking out the pre-release `2.0.0-0` and report back if it works as intended from your side?

**Comment by YehorLitsov** [comment]
@daniel-sc thank you, this pre-release `2.0.0-0` solved the problem for me. Sorry for long reply

**Comment by Hafnernuss** [comment]
If this is completly resolved, maybe consider removing
>Leading/trailing whitespaces are normalized (i.e. collapsed to one space) but not completely trimmed (#28).
from the docs? 🤔

**Comment by michel-jambo** [comment]
Hi @daniel-sc 

I'm having a similar issue where the space between the `<ph>` nodes disappear after rendered on the screen. Do you believe it could be due how angular render things? I'm using version `2.14.3` of the library.

`<unit id="7981621245234768630">
      <notes>
        <note category="location">src/app/random-file.html:52,54</note>
      </notes>
      <segment state="initial">
        <source><ph disp="{{ totalCount }}" equiv="INTERPOLATION" id="0"/> <ph disp="{{itemName}}" equiv="INTERPOLATION_1" id="1"/> found </source>
        <target><ph disp="{{ totalCount }}" equiv="INTERPOLATION" id="0"/> <ph disp="{{itemName}}" equiv="INTERPOLATION_1" id="1"/> trouvé </target>
      </segment>
</unit>`

So, instead of `15 projets trouvé` we get `15projets trouvé`. Adding `&nbsp;` to the html code does not help though and it doesn't not get copied over to the translation file. So far the best solution I could find is adding and empty expression {{ " " }} in the source code.

**Config**:
`"extract-i18n": {
          "builder": "ng-extract-i18n-merge:ng-extract-i18n-merge",
          "options": {
            "buildTarget": "frontend:build",
            "format": "xliff2",
            "includeContext": true,
            "sortNestedTagAttributes": true,
            "prettyNestedTags": false,
            "collapseWhitespace": true,
            "verbose": true,
            "outputPath": "src/i18n",
            "targetFiles": ["messages.en.xlf", "messages.fr.xlf"]
          }
        }`
