### ISSUE TITLE
add to project not possible

### ISSUE THREAD

**Issue by lotterfriends** [daniel-sc/ng-extract-i18n-merge#3]
Node Version: v12.22.9
Angular Version: 13.2.3

when I try to add the configuration to my angular.json/package.json I got following error:
```
✔ Add a command to package.json scripts to to perform extraction and merging of translations? (Y/n) · true
TypeError: Cannot use 'in' operator to search for '0' in apps/my-app/src/i18n/messages.de.xlf
    at __spreadArray (/home/me/projects/my-project/my-app/node_modules/ng-extract-i18n-merge/dist/schematics/ng-add/index.js:15:23)
    at selectTargetFile (/home/me/projects/my-project/my-app/node_modules/ng-extract-i18n-merge/dist/schematics/ng-add/index.js:32:18)
    at /home/me/projects/my-project/my-app/node_modules/ng-extract-i18n-merge/dist/schematics/ng-add/index.js:67:293
    at Array.map (<anonymous>)
    at /home/me/projects/my-project/my-app/node_modules/ng-extract-i18n-merge/dist/schematics/ng-add/index.js:67:259
    at /home/me/projects/my-project/my-app/node_modules/@schematics/angular/utility/workspace.js:40:34
    at processTicksmejections (internal/process/task_queues.js:97:5)
```

It's an nx.dev repo with many apps.

**Comment by lotterfriends** [comment]
translation in angular json could be a string and you expect always an array
https://github.com/daniel-sc/ng-extract-i18n-merge/blob/master/schematics/ng-add/index.ts#L47

checkout node_modules/@angular/cli/lib/config/schema.json line 313
![image](https://user-images.githubusercontent.com/3378880/157425864-3f0f3bd9-60e2-439d-a9ff-78748e89dbba.png)

**Comment by daniel-sc** [comment]
Hi @lotterfriends  
thanks for reporting this and doing the research!
I created a pre release `1.0.3-0` that should have this fixed - can you please check and confirm?

**Comment by lotterfriends** [comment]
Work fine. Thank you  :+1:
