### ISSUE TITLE
Add debug option from xliff-simple-merge

### ISSUE THREAD

**Issue by danjor** [daniel-sc/ng-extract-i18n-merge#33]
Hi,

It should be good to used last version of xliff simple merge + add support of debug option that is available in xliff-simple-merge but not in ng-extract-i18n-merge.

**Comment by daniel-sc** [comment]
@danjor Sorry for the late reply. Would you mind giving some details on what you'd need/like the debug output for? 
(The latest version includes the latest version of xliff-simple-merge already)

**Comment by danjor** [comment]
Thank you for your reply.
I can't remember what was exactly the issue I was facing but I had to do some debugging and finally manage to do using breakpoints, and also I thout the last version ok ng-extract-i18n-merge was not using the last version of xliff-simple-merge but I was wrong.
