### ISSUE TITLE
ng extract-i18n fails if the source file does not exist

### ISSUE THREAD

**Issue by strout** [daniel-sc/ng-extract-i18n-merge#34]
Hi,

I have a project where the source file, messages.xlf, isn't checked into my repository. After switching to ng-extract-i18n-merge v2 and building in a fresh checkout, I get:

```
$ ng extract-i18n
Running ng-extract-i18n-merge for project client-app
running "extract-i18n" ...
An unhandled exception occurred: ENOENT: no such file or directory, open 'src/locale/messages.xlf'
```

This worked when I tried it with an earlier version, maybe v1.3. It looks like it broke with #27 -- it looks like it needs to catch the missing file exception and fall back to the `extract-i18n`-generated file as the "original" source.

As a workaround I've had to change the builder back to @angular-devkit/build-angular:extract-i18n, generate the source xlf file, check it in, then switch back.

**Comment by daniel-sc** [comment]
@strout Thanks for reporting this and doing the analysis!

I'll probably fix this next week - but you'd be very welcome to provide a PR to speed things up ;-)
