### ISSUE TITLE
Support Angular 12/11/..

### ISSUE THREAD

**Issue by LeLunZ** [daniel-sc/ng-extract-i18n-merge#39]
Using angular version 11 (haven't had the time to upgrade)

![Error](https://user-images.githubusercontent.com/31982496/175519778-78ab7226-a878-44ae-9c36-e7e559aba0a6.png)

**Comment by daniel-sc** [comment]
Currently only Angular 13+ is supported. I'd recommend upgrading your project to 14 (or 13). 

If someone is willing to add/test compatibility with older angular versions, I'd be happy to review and assist. Probably I won't find time soon to do it myself.

**Comment by LeLunZ** [comment]
Yeah I know. We hadn’t had the time to upgrade. 
i didn’t see a Version requirement so I thought this should work for most versions.

i changed the angular.json manually, and everything seems to work perfectly. 

Really love this project, as it makes everything much simpler!

**Comment by mpumford** [comment]
I'm seeing this issue on an angular 13 project. It does have some library dependencies that are from older versions but there is no translation text being pulled from these libraries.

Is there any info I can provide to help debug this?

**Comment by daniel-sc** [comment]
@mpumford could you share your package.json and package-lock.json?

**Comment by daniel-sc** [comment]
Closing this, as Angular is not supporting anything pre 14 anyways - see https://angular.io/guide/releases#actively-supported-versions
