### ISSUE TITLE
Cannot read properties of undefined (reading 'attr')

### ISSUE THREAD

**Issue by Khokhlachov** [daniel-sc/ng-extract-i18n-merge#40]
Hi, I faced issue if destination file is not empty.
"@angular/core": "14.0.2",
"ng-extract-i18n-merge": "^2.0.1",

https://www.screencast.com/t/Wn8dB1QxvVP2

**Comment by daniel-sc** [comment]
Hi @Khokhlachov 
thanks for reporting! could you detail what the contents of your destination file (messages.en.xlf, I suppose) is?

**Comment by daniel-sc** [comment]
ok - just read the referenced issue - now I think the problem is clear and solvable :)

**Comment by Khokhlachov** [comment]
> ok - just read the referenced issue - now I think the problem is clear and solvable :)

In my case we use third party tool for translators (poeditor.com) so each export will forced to this case...
Thanks for quick response !
