### ISSUE TITLE
Whitespaces not trimmed properly?

### ISSUE THREAD

**Issue by Hafnernuss** [daniel-sc/ng-extract-i18n-merge#43]
**Describe the bug**
I am not sure if it's a bug as I am not sure I fully know if this is intended behaviour or not.
I get a lot of warnings like this:
![image](https://user-images.githubusercontent.com/18393658/184302094-74a62be6-a7ab-482d-b824-0fa605b4e188.png)

Where some of the lines look like that:
```html
<button class="col-4 btn w-100 btn-primary block" type="submit" (click)="onLogin()" i18n="Login|Auth@@Login">
    Login
</button>
```

This causes the translator to pick the string up as " Login " rather than "Login".
Funny enough, the translation units seem to look "as expected": `<source>Login</source>`

**Setup/Configuration**
```js
"extract-i18n": {
          "builder": "ng-extract-i18n-merge:ng-extract-i18n-merge",
          "options": {
            "browserTarget": "sportsense-tms:build",
            "format": "xlf",
            "collapseWhitespace": true,
            "trim": true,
            "includeContext": true,
            "outputPath": "src/locale",
            "targetFiles": [
              "messages.en.xlf",
              "messages.de.xlf"
            ]
          }
        }
```

and some translations like:
```html
  <button class="col-4 btn w-100 btn-primary block" type="submit" (click)="onLogin()" i18n="Login|Auth@@Login">
    Login
  </button>
```

and
```html
<button class="btn btn-primary" (click)="onLogin()" id="login" i18n="Login|ResetPassword@@Login">Login</button>
```

**Expected behavior**
No warnings

**Version (please complete the following information):**
 - Angular: 13
 - ng-extract-i18n-merge version: 2.1.2

**Additional context**
[angular issue](https://github.com/angular/angular/issues/13114)

**Comment by daniel-sc** [comment]
@Hafnernuss This is from the angular i18n extraction. See https://stackoverflow.com/q/70900706/2544163

**Comment by Hafnernuss** [comment]
so this means there is nothing I can do? I have to break sometimes because of line length limits...

**Comment by daniel-sc** [comment]
I'd recommend too use line breaks before and after all texts where this problem occurs. (This is how I do it in my project.)

Besides this, there is little you can do, I'm afraid.
