### ISSUE TITLE
Add support for a pseudo language

### ISSUE THREAD

**Issue by davidyoung77** [daniel-sc/ng-extract-i18n-merge#48]
**Is your feature request related to a problem? Please describe.**
Not a problem but an enhancement.

As a QA engineer I would like the ability to be able to confirm that new texts were indeed marked for translation

**Describe the solution you'd like**
A good standard for confirming that texts are indeed marked for translation is as follows

I would like the ability to create a pseudo language localization file, that I can then serve.

Details:
- The pseudo language code can be 'zz' by default and should be overridable
- New trans unit target texts would be the same as the source texts but appended with the target language code
- The target state should be set to final
- The target will always be set as `${target language code}- Source text`, regardless of whether `newTranslationTargetsBlank` is set to true or omit, as this is the whole point of the pseudo langage

Example:
```
<trans-unit id="myUniqueId" datatype="html">
  <source>Source text</source>
  <target state="final">zz- Source text</target>
  <note priority="1" from="description">The description</note>
  <note priority="1" from="meaning">The meaning</note>
</trans-unit>
 ```

**Describe alternatives you've considered**
Doing this manually or adding this feature to this lib

**Additional context**
Thanks again for your work with this lib, @daniel-sc Let me know if this makes sense. Also are there any missing details we need to think through?

**Comment by daniel-sc** [comment]
hi @davidyoung77 

If I understand the issue correctly, this can be done with a simple shell one liner:
```bash
cp messages.en.xlf messages.zz.xlf && sed -i 's/<target[^>]*>/\0zz- /g' messages.zz.xlf
```
(Assuming messages.en.xlf is configured as `sourceLanguageTargetFile`.)

If this indeed solves your request, I'd rather _not_ complicate this libs config but suggest you use the script at the appropriate place (e.g. before running your QA check or as a git pre-commit hook.

**Comment by davidyoung77** [comment]
Thanks @daniel-sc I understand wanting to keep this out of the library

My use case is slightly different than that.
- I need to support both Mac and windows, so I can do the same thing with a javascript tool
- I set` "newTranslationTargetsBlank": "omit",` so there is no target in the source file, but I can either prefix the source or copy the source and create a target.

I will close this issue and create a script to handle this.
