### ISSUE TITLE
Source must be equal to target in main file

### ISSUE THREAD

**Issue by masartbenji** [daniel-sc/ng-extract-i18n-merge#49]
Hello,

It can interesting to have an option to allow the possibility to have, in main translation file, source field to be equal to target.

For example, if I set a translation in Angular, then I launch your script, the source tag is correctly set but not the target

**Comment by daniel-sc** [comment]
Hi @masartbenji 

Not sure if I did understand what you want to achieve. You'd like a translation file where source and target are equal? E.g. a messages.en.xlf (assuming the texts in your templates are English). This could be done by using the configuration option `sourceLanguageTargetFile`. Would this solve the issue? (In case not, a more concrete example would be appreciated :) )

**Comment by masartbenji** [comment]
Hello @daniel-sc 

It's fine, I used the old version of the library, but now I updated library and it works fine.

Best regards.
