### ISSUE TITLE
Additional logging // "Merge and normalize" step hangs

### ISSUE THREAD

**Issue by TTvanWillegen** [daniel-sc/ng-extract-i18n-merge#56]
Is there a way to show additional logging during the merge? 
I'm running this program on my existing translation base (+/- 3500 translations; merged before with xliffmerge, moved to this due to the console error) and it takes >10 min and is still not finished. I'd like to know if it crashed on something or if it is still trying its best.

**Comment by daniel-sc** [comment]
@TTvanWillegen currently there is only little output, but it should not take that long.. 
Is there any output at all? What nodejs version and OS are you running?

**Comment by TTvanWillegen** [comment]
Hi Daniel,
I'm currently on Node version 16.16.0 and Angular version 14.2.3.

It only outputs the following and then hangs:
![image](https://user-images.githubusercontent.com/15815200/198982188-119547af-5bea-4268-a7f3-63283d030d98.png)

"extract-i18n" in angular.json looks like this:
``` json
"extract-i18n": {
          "builder": "ng-extract-i18n-merge:ng-extract-i18n-merge",
          "options": {
            "browserTarget": "default:build",
            "format": "xlf",
            "outputPath": "src/locale",
            "includeContext": true,
            "targetFiles": [
              "messages.es-ES.xlf",
              "messages.nl-NL.xlf"
            ],
            "trim": true
          }
        }
```


Folder structure looks like this:
![image](https://user-images.githubusercontent.com/15815200/198982588-62af6f30-197f-48e0-82b2-f19500bd83d9.png)

**Comment by daniel-sc** [comment]
@TTvanWillegen thanks for the update - would it be possible to share the messages.xlf (before and after the extraction) and messages.es-ES.xlf? In case you'd rather share it privately: daniel-schreiber@gmx.de

**Comment by TTvanWillegen** [comment]
@daniel-sc Thank you, I've sent them to you via e-mail. You should've received them by now.

**Comment by daniel-sc** [comment]
thanks I'll look into this..

**Comment by daniel-sc** [comment]
Update: still working on this. Looks like this is caused by really bad performance when fuzzy matching many entries. The fix is almost ready though..

**Comment by TTvanWillegen** [comment]
Thank you very much; I've re-installed, so it would grab the v1.0.1 of xliff-simple-merge and can confirm the performance is way better 👍
