### ISSUE TITLE
Same text with different note shouldn't be merged

### ISSUE THREAD

**Issue by sandrica89** [daniel-sc/ng-extract-i18n-merge#61]
**Describe the bug**
In html file : 
```
<p i18n="|context1">My text</p>
<p i18n="|context2">My text</p>
```
After running `ng extract-i18n`, I got in my XLF file something like : 
```
<trans-unit id="trans-id" datatype="html">
	<source>My text</source>
	<target state="new">My text</target>
	<context-group purpose="location">
	  <context context-type="sourcefile">my.html</context>
	  <context context-type="linenumber">1</context>
	</context-group>
	<context-group purpose="location">
	  <context context-type="sourcefile">my.html</context>
	  <context context-type="linenumber">2</context>
	</context-group>
	<note priority="1" from="description">context2</note>
</trans-unit>
```

**Setup/Configuration**
NA

**Expected behavior**
I should have : 
```
<trans-unit id="trans-id1" datatype="html">
	<source>My text</source>
	<target state="new">My text</target>
	<context-group purpose="location">
	  <context context-type="sourcefile">my.html</context>
	  <context context-type="linenumber">1</context>
	</context-group>
	<note priority="1" from="description">context1</note>
</trans-unit>
<trans-unit id="trans-id2" datatype="html">
	<context-group purpose="location">
	  <context context-type="sourcefile">my.html</context>
	  <context context-type="linenumber">2</context>
	</context-group>
	<note priority="1" from="description">context2</note>
</trans-unit>
```

**Screenshots**
NA

**Version (please complete the following information):**
 - Angular: 15.0.4
 - OS: Ubuntu
 - nodejs: 14.21.1 or 16.13.0
 - ng-extract-i18n-merge version: 2.5.0

**Additional context**
NA

**Comment by daniel-sc** [comment]
Hi @sandrica89 

I looked into this and I think this follows the standard angular way of handling "descriptions".
See "HOW MEANINGS CONTROL TEXT EXTRACTION AND MERGES" on https://angular.io/guide/i18n-common-prepare#add-helpful-descriptions-and-meanings

So either you should add some different "meaning" (`<p i18n="meaning1|context1">My text</p><p i18n="meaning2|context2">My text</p>`) or (recommended) add explicit translation IDs (<p i18n="|context1@@ID1">My text</p><p i18n="|context2@@ID2">My text</p>`).

Please let me know if I missed something here!
