### ISSUE TITLE
Use deprecated sourcemap-codec v1.4.8

### ISSUE THREAD

**Issue by aljaznuncic** [daniel-sc/ng-extract-i18n-merge#62]
**Describe the bug**
Use deprecated sourcemap-codec v1.4.8. Please use @jridgewell/sourcemap-codec instead.

**Setup/Configuration**
I use ng-extract-i18n-merge: 2.5.0

**Version:**
 - Angular: 15.1.3
 - OS: Ubuntu 22.04
 - nodejs: v18.12.1
 - ng-extract-i18n-merge version: 2.5.0

**Comment by daniel-sc** [comment]
@aljaznuncic using 2.5.1 in an v15 angular project should not give this warning any more.
