### ISSUE TITLE
Do we need @angular-devkit/build-angular

### ISSUE THREAD

**Issue by aljaznuncic** [daniel-sc/ng-extract-i18n-merge#71]
Do we really need @angular-devkit/build-angular as a dependency. It contains protractor, which is deprecated and contains dependencies with vulnerabilities (xml2js@0.4.23 and request@2.88.2)

**Comment by daniel-sc** [comment]
@aljaznuncic Yes - this lib replaces - and internally invokes- the "extract-i18n"-builder from  @angular-devkit/build-angular. Would you have any other idea?

Furthermore any angular project depends on this dependency to build - doesn't it?
