### ISSUE TITLE
`newTranslationTargetsBlank` ignored when using `omit` in translation files

### ISSUE THREAD

**Issue by FrostKiwi** [daniel-sc/ng-extract-i18n-merge#74]
**Describe the bug**
When using `"newTranslationTargetsBlank": "omit"` in combination with `"trim": true`, then omit is ignored when `extract-i18n` trims white space. It just pastes new `<target>`s with the state new applied.

**Setup/Configuration**
```json
"extract-i18n": {
                    "builder": "ng-extract-i18n-merge:ng-extract-i18n-merge",
                    "options": {
                        "browserTarget": "<redacted>:build",
                        "outputPath": "src/locale",
                        "targetFiles": [
                            "messages.ja.xlf",
                            "messages.de.xlf",
                            "messages.ru.xlf"
                        ],
                        "sourceFile": "messages.xlf",
                        "includeContext": true,
                        "newTranslationTargetsBlank": "omit",
                        "collapseWhitespace": true,
                        "trim": true
                    }
                },
```

**Expected behavior**
`"newTranslationTargetsBlank": "omit"` should be respected, even with `"trim"`: true

**Screenshots**
`<target>` added in the translation files, when trimming white space, but not everywhere else
![image](https://github.com/daniel-sc/ng-extract-i18n-merge/assets/60887273/0b70f93b-cb21-40c6-b60d-611a2f3af70b)

**Version (please complete the following information):**
 - Angular: [e.g. 13.3.0]
 - OS: [e.g. Win10]
 - nodejs: [e.g. 16.20.2]
 - ng-extract-i18n-merge version: [e.g. 2.7.0]

**Comment by daniel-sc** [comment]
@FrostKiwi Please check out the latest version 2.7.1 and reach out if there are still issues! (Thanks  for this issue!)

**Comment by FrostKiwi** [comment]
> @FrostKiwi Please check out the latest version 2.7.1 and reach out if there are still issues! (Thanks for this issue!)

Can confirm this being xied with the update to 2.7.1 👍
