### ISSUE TITLE
Leave non-translated unit blank

### ISSUE THREAD

**Issue by Martin-Hogge** [daniel-sc/ng-extract-i18n-merge#8]
Actually when their is a new translation, the `target` takes the `source` value as the default one. Is their a way to leave it blank until a translation is set ?

Thank you.

**Comment by daniel-sc** [comment]
Hi @Martin-Hogge 
thanks for helping improving this tool!

I'd question if this is actually what you want. This would lead to missing texts in the application - I'd argue you'd rather have untranslated texts than missing texts?

(Of course if there is a relevant scenario where this would be useful, I'd be happy to include a corresponding config option)

**Comment by Martin-Hogge** [comment]
In my case this is relevant for 2 reasons: 
- We are actually passing the `xlf` file to a custom application used by translators and they are used to check over blank lines for a quick view of what should be translated.
- In some use case of our app, it's better to have no translation than something that could be misleading.

I imagine you could add an option like `leaveUntranslatedUnitBlank` that would be µ false` by default as I understand that this is the most used scenario.

Thank you for your reactiveness !

**Comment by daniel-sc** [comment]
OK, I'll add this in the next days. 
In case you'd have capacity for preparing a PR, this would be very welcome! (You'd probably need to start with a change to the upstream https://github.com/daniel-sc/ng-extract-i18n-merge
