### ISSUE TITLE
Invalid character in entity name

### ISSUE THREAD

**Issue by Hafnernuss** [daniel-sc/ng-extract-i18n-merge#87]
After upgrading from `2.7.1` to any version after that (including `2.8.0-0`, extraction fails with the following message:

```
An unhandled exception occurred: Invalid character in entity name
Line: 0
Column: 56
Char:  
See "C:\Users\xxxx1\AppData\Local\Temp\ng-ualXsF\angular-errors.log" for further details.
```
After fiddling around in [`translationFileSerialization.js`](https://github.com/daniel-sc/ng-extract-i18n-merge/blob/a30610de402abaa57492fba8325aa6a3f7ed8e8a/src/model/translationFileSerialization.ts#L139) it turns out, that a meaning with an `&` was the culprit. 

This was no issue prior to `2.8.1`. It's not a problem for me, but I guess it is some sort of bug?

**Comment by daniel-sc** [comment]
@Hafnernuss Thanks for this detailed report! Indeed, the implementation changed significantly with 2.8.0 - so probably that introduced this bug.

**Comment by Hafnernuss** [comment]
You're welcome, thanks for the awsome package ;)

I suspect this affects other formats as well, I am still using the old xlf1.
