### ISSUE TITLE
Produce metadata too

### ISSUE THREAD

**Issue by worthy7** [daniel-sc/ng-extract-i18n-merge#91]
**Is your feature request related to a problem? Please describe.**
The latest `extract-i18n` from Angular will produce some metadata for each translation. However, this package does not produce that metadata in the xlf file. I expected it to be the same.

**Describe the solution you'd like**
Produce the XLF files with all metadata included, same as native Angular extract-i18n

ng-extract-i18n-merge
![image](https://github.com/daniel-sc/ng-extract-i18n-merge/assets/4762399/1501c731-5b13-4bf3-9763-b94f7188d526)

native angular 17 extract
![image](https://github.com/daniel-sc/ng-extract-i18n-merge/assets/4762399/e47bf9f0-3591-47c9-962e-ece2ba4e7169)

**Comment by worthy7** [comment]
Related https://github.com/angular/angular/issues/37202

**Comment by daniel-sc** [comment]
@worthy7 did you set the config option `includeContext: true`? All options are documented in the Readme and have sensible defaults for most projects.

**Comment by worthy7** [comment]
Sorry, I missed that. I would argue that the default should be `true`, same as with the native `extract-i18n`.
