### ISSUE TITLE
includeContext option description incorrectly refers to notes tag

### ISSUE THREAD

**Issue by co-dax** [daniel-sc/ng-extract-i18n-merge#95]
At the following link [https://github.com/daniel-sc/ng-extract-i18n-merge?tab=readme-ov-file#configuration](https://github.com/daniel-sc/ng-extract-i18n-merge?tab=readme-ov-file#configuration) the docs are saying the following in the context of `includeContext` option:

> Whether to include the context information (like notes) in the translation files. This is useful for sending the target translation files to translation agencies/services. When sourceFileOnly, the context is retained only in the sourceFile.

...but the `note` tag in preserved in the destination/merged file which should be the correct behaviour since `note` tag in outside of `context-group` to which the property `includeContext ` is (at least should be) referring.

So I would say that the excerpt:
> (like notes)

...should be removed from the link I reported above.

**Comment by daniel-sc** [comment]
@co-dax , @doggy8088 I'm not sure I understand your point(s).
1. Which version(s) are you using?
2. I'm pretty sure the documentation matches the actual behavior: when `includeContext: false` (the default value), then the `note` node is _not_ included in the translation files. Can you please double check and/or give a reproduction?
3. Maybe this is more about naming and/or defaults? The configuration `includeContext` does not specifically adress the xml node `context-group`, but "contextual information" such as location/meaning/description (e.g. with XLF2 naming of nodes is different).

Or this this about something else entirely?

**Comment by doggy8088** [comment]
@daniel-sc Please check my repo: https://github.com/doggy8088/ng-i18n-demo/tree/ng-extract-i18n-merge

At first, check this commit: https://github.com/doggy8088/ng-i18n-demo/commit/a45ff6d2d9fd9174f5a880accbe3274f5155baa3?diff=unified&w=0

After I run `ng add ng-extract-i18n-merge` and `ng extract-i18n` command. The `<note>` has been removed.

![image](https://github.com/daniel-sc/ng-extract-i18n-merge/assets/88981/3ce14da1-622a-456d-a3a6-e02112498ede)

https://github.com/doggy8088/ng-i18n-demo/commit/a45ff6d2d9fd9174f5a880accbe3274f5155baa3?diff=unified&w=0#diff-e2cae9b9c1350d0b44c90db489eb38f00c905a1ecd9e3a7c52988c389d0730faR9-R12

I think the `<context-group>` should be removed by default, but the `<note priority="1" from="description">放置在首頁的招呼語</note>` should be kept. It's different.

**Comment by co-dax** [comment]
@daniel-sc I was using version 1.4 and with that version it used to work as I described above. I have just upgraded to version 2.9.1 and now it works as described by @doggy8088 just above. I thnk @doggy8088 is right in his last comment on how it should be working.

**Comment by doggy8088** [comment]
@daniel-sc  Good job! 😃 Thanks! 👍
